pipeline {
    agent any
    environment {
        AWS_ACCOUNT = '856782348879'
        ECR_REGISTRY = "${AWS_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com"
        CLUSTER_NAME = 'three-tier-clusters'
        REGION = 'us-east-1'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/sohailshaikh71/aws-three-tier-web-architecture.git'
            }
        }
        stage('Build Docker Images') {
            steps {
                dir('application-code') {
                    sh 'docker build -t ${ECR_REGISTRY}/app-tier:latest -f app-tier/Dockerfile app-tier/'
                    sh 'docker build -t ${ECR_REGISTRY}/web-tier:latest -f web-tier/Dockerfile web-tier/'
                }
            }
        }
        stage('Push to ECR') {
            steps {
                sh '''
                    aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                    docker push ${ECR_REGISTRY}/app-tier:latest
                    docker push ${ECR_REGISTRY}/web-tier:latest
                '''
            }
        }
        stage('Deploy to EKS') {
            steps {
                sh '''
                    aws eks update-kubeconfig --region ${REGION} --name ${CLUSTER_NAME}
                    kubectl apply -f application-code/app-tier-deployment.yaml
                    kubectl apply -f application-code/web-tier-deployment.yaml
                    kubectl apply -f application-code/services.yaml
                '''
            }
        }
    }
}
